stages:
  - test
  - build
  - deploy

variables:
  GOOGLE_CREDENTIALS: $TF_GOOGLE_CREDENTIALS
  GOOGLE_PROJECT_ID: $TF_GOOGLE_PROJECT_ID
  SLACK_USER_TOKEN: $TF_SLACK_USER_TOKEN
  SLACK_MESSAGE_CHANNEL: $TF_SLACK_MESSAGE_CHANNEL
  SLACK_CHANNEL_IDS: $TF_SLACK_CHANNEL_IDS
  SLACK_TEAM_ID: $TF_SLACK_TEAM_ID

test:
  stage: test
  image: node:18
  script:
    - npm install
    - npm test

build:
  stage: build
  image: hashicorp/terraform:latest
  script:
    - cd terraform
    - terraform validate

deploy:
  stage: deploy
  image: hashicorp/terraform:latest
  script:
    - cd terraform
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  dependencies:
    - build
  artifacts:
    paths:
      - terraform/tfplan
